### ISSUE TITLE
我的天呐，这么优秀的项目怎么会报错

### ISSUE THREAD

**Issue by wangguangzhong** [cifeng/cfs#1]
请您抽时间看一下，我真的不知道怎么解决 ，谢谢
Error:(37, 27) java: 程序包ytx.org.apache.http不存在
Error:(38, 27) java: 程序包ytx.org.apache.http不存在
Error:(39, 42) java: 程序包ytx.org.apache.http.client.methods不存在
Error:(40, 42) java: 程序包ytx.org.apache.http.client.methods不存在
Error:(41, 42) java: 程序包ytx.org.apache.http.client.methods不存在
Error:(42, 34) java: 程序包ytx.org.apache.http.entity不存在
Error:(43, 39) java: 程序包ytx.org.apache.http.impl.client不存在
Error:(44, 35) java: 程序包ytx.org.apache.http.message不存在
Error:(45, 32) java: 程序包ytx.org.apache.http.util不存在
Error:(1632, 17) java: 找不到符号
  符号:   类 HttpRequestBase
  位置: 类 com.platform.cfs.cloopen.CCPRestSDK
Error:(1637, 17) java: 找不到符号
  符号:   类 HttpRequestBase
  位置: 类 com.platform.cfs.cloopen.CCPRestSDK
Error:(1719, 39) java: 找不到符号
  符号:   类 AbstractHttpMessage
  位置: 类 com.platform.cfs.cloopen.CCPRestSDK
Error:(1724, 41) java: 找不到符号
  符号:   类 AbstractHttpMessage
  位置: 类 com.platform.cfs.cloopen.CCPRestSDK
Error:(1734, 36) java: 找不到符号
  符号:   类 AbstractHttpMessage
  位置: 类 com.platform.cfs.cloopen.CCPRestSDK
G:\Amember\cfs\src\main\java\com\platform\cfs\cloopen\utils\CcopHttpClient.java
Error:(14, 39) java: 程序包ytx.org.apache.http.conn.scheme不存在
Error:(15, 36) java: 程序包ytx.org.apache.http.conn.ssl不存在
Error:(16, 39) java: 程序包ytx.org.apache.http.impl.client不存在
Error:(20, 10) java: 找不到符号
  符号:   类 DefaultHttpClient
  位置: 类 com.platform.cfs.cloopen.utils.CcopHttpClient

**Comment by wangguangzhong** [comment]
已star

**Comment by cifeng** [comment]
因为用到了第三方短信平台提供的一个jar包 需要手动打包到maven库中
mvn install:install-file -Dfile=D:\httpclient.jar -DgroupId=cloopen -DartifactId=httpclient -Dversion=1.0.1 -Dpackaging=jar
具体的jar包 我会传到项目doc/lib下

**Comment by wangguangzhong** [comment]
您好 ，为何还提示以下错误，是需要先配置短信平台吗？
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:157) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at com.platform.cfs.Application.main(Application.java:19) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.1.2.RELEASE.jar:2.1.2.RELEASE]
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:206) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	... 13 common frames omitted

**Comment by wangguangzhong** [comment]
您好，短信平台还需要配置吗，我直接运行了一下报错误





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"刺风"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月25日(星期三) 中午1:45
收件人:&nbsp;"cifeng/cfs"<cfs@noreply.github.com&gt;;
抄送:&nbsp;"。"<2658675006@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cifeng/cfs] 我的天呐，这么优秀的项目怎么会报错 (#1)




因为用到了第三方短信平台提供的一个jar包 需要手动打包到maven库中
 mvn install:install-file -Dfile=D:\httpclient.jar -DgroupId=cloopen -DartifactId=httpclient -Dversion=1.0.1 -Dpackaging=jar
 具体的jar包 我会传到项目doc/lib下

**Comment by cifeng** [comment]
https://blog.csdn.net/l31299/article/details/79932694
